// <auto-generated />
using System;
using EquipmentBorrowing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipmentBorrowing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EquipmentBorrowingDbContext))]
    partial class EquipmentBorrowingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("EquipmentBorrowing.Domain.Borrowing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateBorrowed")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpectedReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.HasIndex("ExpectedReturnDate");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "Status");

                    b.ToTable("Borrowings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Borrowings_ValidStatus", "\"Status\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsAvailable");

                    b.ToTable("Equipment", (string)null);
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAllowedToBorrow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumActiveBorrowings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students", null, t =>
                        {
                            t.HasCheckConstraint("CK_Students_MaximumActiveBorrowings_NonNegative", "\"MaximumActiveBorrowings\" >= 0");
                        });
                });

            modelBuilder.Entity("EquipmentBorrowing.Domain.Borrowing", b =>
                {
                    b.HasOne("EquipmentBorrowing.Domain.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EquipmentBorrowing.Domain.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
